---
- hosts: localhost
  tasks:
  - name: Copy wallpaper
    copy:
      src: files/ansible_wallpaper.jpg
      dest: /usr/share/backgrounds/ansible_wallpaper.jpg
      owner: root
      group: root
    
  - name: Chnage the wallpaper
     dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "file:///usr/share/backgrounds/ansible_wallpaper.jpg"
      state: present
