---
- hosts: localhost
  become: yes
  tasks:
  - name: Copy wallpaper
    copy:
      src: files/ansible_wallpaper.jpg
      dest: /usr/share/backgrounds/ansible_wallpaper.jpg
      owner: root
      group: root
 
 
- hosts: localhost
  tasks:
  - name: Chnage the wallpaper, theme and icons
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible_wallpaper.jpg'"
      state: present
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Arc-Dark'"
      state: present
      key: "/org/gnome/desktop/interface/icon-theme"
      value: "'TelaBudgie'"
      state: present
