---
- hosts: localhost
  become: yes
  tasks:
  - name: Copy wallpaper
    copy:
      src: files/ansible_wallpaper.jpg
      dest: /usr/share/backgrounds/ansible_wallpaper.jpg
      owner: root
      group: root
 
 
- hosts: localhost
  become: yes
  become_user: hussain
  tasks:
  - name: Chnage the wallpaper
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible_wallpaper.jpg'"
       tate: present
